# Generated by Django 3.2.7 on 2021-09-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='bill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='item_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
