# Generated by Django 3.2.7 on 2021-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
