# Generated by Django 3.2.7 on 2021-10-06 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecus',
            name='registered_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 54, 26, 868622), null=True),
        ),
    ]
