# Generated by Django 3.2.7 on 2021-10-07 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0002_alter_ecus_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecus',
            name='registered_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
