# Generated by Django 3.2.7 on 2021-10-27 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocksmanagement', '0002_auto_20211021_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='registered_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
