# Generated by Django 3.2.7 on 2021-09-20 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0003_auto_20210920_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecus',
            name='registered_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 20, 20, 19, 35, 637747), null=True),
        ),
    ]
