# Generated by Django 3.2.7 on 2021-10-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
