# Generated by Django 3.2.7 on 2021-09-14 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0004_alter_stock_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
