# Generated by Django 3.2.7 on 2021-09-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0005_auto_20210920_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecus',
            name='registered_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 22, 17, 37, 1, 368275), null=True),
        ),
    ]
