# Generated by Django 3.2.7 on 2021-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0006_auto_20210914_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, choices=[('Finished Goods(제품)', 'Finished Goods(제품)'), ('Merchandise(상품)', 'Merchandise(상품)'), ('Raw Material(원자재)', 'Raw Material(원자재)'), ('Semi-Finished Goods(반제품)', 'Semi-Finished Goods(반제품)')], max_length=100, null=True),
        ),
    ]
