# Generated by Django 3.2.7 on 2021-09-22 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0006_alter_ecus_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecus',
            name='registered_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 22, 17, 52, 7, 441400), null=True),
        ),
    ]
