# Generated by Django 3.2.7 on 2021-09-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0007_alter_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ecus_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
