# Generated by Django 3.2.7 on 2021-09-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0008_stock_ecus_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
