# Generated by Django 3.2.7 on 2021-09-15 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocksmanagement', '0009_auto_20210915_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('type_code', models.CharField(blank=True, max_length=3, null=True)),
                ('goods_no', models.IntegerField(blank=True, null=True)),
                ('npl_sp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('hs', models.CharField(blank=True, max_length=10, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_country', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('unit_price_taxed', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=15, null=True)),
                ('total_2', models.FloatField(blank=True, null=True)),
                ('unit_2', models.CharField(blank=True, max_length=15, null=True)),
                ('nt_value', models.FloatField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('tax_cost', models.FloatField(blank=True, null=True)),
                ('partner', models.CharField(blank=True, max_length=50, null=True)),
                ('bill', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
