# Generated by Django 3.2.7 on 2021-09-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0010_ecus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecus',
            name='bill_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='registered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
