# Generated by Django 3.2.7 on 2021-09-15 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocksmanagement', '0016_auto_20210915_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ecus_code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=4, null=True)),
                ('ecus', models.CharField(blank=True, max_length=20, null=True)),
                ('name_2', models.CharField(blank=True, max_length=20, null=True)),
                ('description_2', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_2', models.CharField(blank=True, max_length=4, null=True)),
                ('bom', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('finish_product', models.IntegerField(blank=True, null=True)),
                ('finish_product_convert', models.FloatField(blank=True, null=True)),
                ('finish_product_inventory', models.FloatField(blank=True, null=True)),
                ('finish_product_exchange', models.FloatField(blank=True, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
