# Generated by Django 3.2.7 on 2021-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0017_bom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='rm_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
