# Generated by Django 3.2.7 on 2021-09-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocksmanagement', '0018_bom_rm_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('erp_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ecus_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('ecus_unit', models.CharField(blank=True, max_length=4, null=True)),
                ('unit', models.CharField(blank=True, max_length=4, null=True)),
                ('e21', models.IntegerField(blank=True, null=True)),
                ('b13', models.IntegerField(blank=True, null=True)),
                ('a42', models.IntegerField(blank=True, null=True)),
                ('e52', models.IntegerField(blank=True, null=True)),
                ('ecus', models.IntegerField(blank=True, null=True)),
                ('rm_stock', models.IntegerField(blank=True, null=True)),
                ('fg_stock', models.IntegerField(blank=True, null=True)),
                ('wip_stock', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
