# Generated by Django 3.2.7 on 2021-09-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksmanagement', '0019_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='ecus_code',
            field=models.CharField(default='Missing', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='erp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ecus',
            name='npl_sp_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
