# Generated by Django 3.2.7 on 2021-10-27 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iob_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='takein',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='takeout',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='IOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('take_in', models.IntegerField()),
                ('take_out', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'code', 'date')},
            },
        ),
    ]
