# Generated by Django 3.2.7 on 2021-10-27 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iob_demo', '0002_auto_20211027_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsTakeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cd_no', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsTakeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_out_no', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='takein',
            name='cd_no',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='client',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='code',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='date',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='description',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='name',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='price',
        ),
        migrations.RemoveField(
            model_name='takein',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='client',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='code',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='description',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='price',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='take_out_no',
        ),
        migrations.RemoveField(
            model_name='takeout',
            name='unit',
        ),
        migrations.AlterField(
            model_name='takein',
            name='take_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='takeout',
            name='take_out',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='CheckTakeIn',
        ),
        migrations.DeleteModel(
            name='CheckTakeOut',
        ),
        migrations.AddField(
            model_name='takein',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_ins', to='iob_demo.itemstakein'),
        ),
        migrations.AddField(
            model_name='takeout',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_outs', to='iob_demo.itemstakeout'),
        ),
    ]
