# Generated by Django 3.2.7 on 2021-10-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iob_demo', '0004_auto_20211028_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstakein',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemstakeout',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
