# Generated by Django 3.2.7 on 2021-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iob_demo', '0006_alter_iob_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstakeout',
            name='take_out_no',
        ),
        migrations.AddField(
            model_name='itemstakeout',
            name='invoice_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemstakein',
            name='invoice_no',
            field=models.CharField(max_length=100),
        ),
    ]
