# Generated by Django 3.2.7 on 2021-10-29 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iob_demo', '0007_auto_20211028_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='iob',
            name='unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='iob',
            unique_together={('client', 'code', 'date', 'unit')},
        ),
    ]
