# Generated by Django 3.2.7 on 2021-09-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hscode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='description',
        ),
        migrations.RemoveField(
            model_name='heading',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subheading',
            name='id',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hscode.section'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hscode.chapter'),
        ),
        migrations.AlterField(
            model_name='heading',
            name='no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subheading',
            name='no',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hscode.heading')),
                ('subheading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hscode.subheading')),
            ],
        ),
    ]
