# Generated by Django 3.2.7 on 2021-09-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hscode', '0003_auto_20210922_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
